# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
