# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_auto_20170317_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Code Fellows', max_length=128),
            preserve_default=False,
        ),
    ]
